%---------------------------------------------------------------------------------------------------
% For Paper
% "Gradient-based Cooperative Control ofquasi-Linear Parameter Varying Vehicleswith Noisy Gradients"
% by Adwait Datar, Antonio Mendez Gonzalez and Herbert Werner
% Copyright (c) Institute of Control Systems, Hamburg University of Technology. All rights reserved.
% Licensed under the GPLv3. See LICENSE in the project root for license information.
% Author(s): Adwait Datar
%---------------------------------------------------------------------------------------------------
% This script is used to plot the data generated by the
% Main_quadrotor_example.m to produce Fig. 2 from the above paper
%% Plot results parameter sweep
clear
clc
%% Performance curves
id=1; % represents the fixed value of kp
figure()
for counter=1:10
filename=['lib2\data\mult_flag_noise_non_causal_61_noise_',num2str(counter-1)];
plot_data_perf(id,filename,counter)
hold on    
end
xlabel('k_d')
ylabel('\alpha')
ylim([0,0.2])
title('Nominal Perf vs Noise robustness: ZF')



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function []=plot_data_perf(id,file,counter)
    save_path=['.\',file];
    data=load(save_path,'alpha_best','kd','kp');
    alpha_best=data.alpha_best;
    kd=data.kd;
    kp=data.kp;
    kd_kp_ratio=kd./kp(id);
    plot(kd_kp_ratio,alpha_best(id,:),'Color',[counter/11 0 (11-counter)/11],'LineWidth',1)    
end